name             'infl-recipes'
maintainer       'Influitive'
maintainer_email 'dev@influitive.com'
license          'MIT'
description      'Cookbook for managing Influitive custom recipes'
long_description 'Cookbook for managing Influitive custom recipes'
version          '0.0.1'
supports         'mac_os_x'
depends          'sprout-base'
depends          'sprout-osx-apps'
depends          'homebrew'
